### ISSUE TITLE
Can see "suggestion" rules on user home

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/tools-issues#100]
### Version

v2.1.33

### Description

On my user home interface on the dashboard, under the category "rules, i can see the "suggestions" rules. 

### Expected behaviour

I should only see it on my admin home interface

### Reproduction steps

```bash
1. go to https://dashboard.kobralost-rp.com/user/1/home
2. Search for the "suggestions" rules
```

### Screenshots

![image](https://github.com/KB-RolePlay/tools-issues/assets/46120142/c97834e1-63f1-48c5-8037-fe3f7c327637)

**Comment by hugoheml** [comment]
Resolved by @talarmin29
