### ISSUE TITLE
add first join date on user profile on dashboard

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/tools-issues#101]
### Description

Add an information about the date of the first join of an user on the server (example in 'Additional Context')

### Additional Context

![image](https://github.com/KB-RolePlay/tools-issues/assets/46120142/dc3c10ee-2a07-4656-b0e5-684735912a0d)

**Comment by Bobninou0030** [comment]
Already on user profil on top of the page @Pikabois
So you can close your issue 😉

**Comment by Pikabois** [comment]
oh yeah ok im blind sorry 😅
