### ISSUE TITLE
Discord, Bug with /moove

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/tools-issues#107]
### Description

If you /moove someone onto your channel, if he stream his screen, stop it, and restart another stream, he will not be able to stream back. 

### Reproduction steps

```bash
1. /moove someone to your channel
2. Ask him to start stream
3. Ask him to stop the stream
4. Ask him to try to start another stream
```

**Comment by talarmin29** [comment]
Not fixed

**Comment by hugoheml** [comment]
Resolved in latest releases.
