### ISSUE TITLE
Punishment categories

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/tools-issues#112]
### Version

v2.2.4

### Description

Duplicate categories

### Reproduction steps

```bash
1. Admin dashboard
```

### Screenshots

![Capture](https://github.com/KB-RolePlay/tools-issues/assets/21173205/533d8ae9-36ee-4707-a26b-5afbf75259cf)

**Comment by hugoheml** [comment]
Solved on `v2.3.13`
