### ISSUE TITLE
Refunds

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/tools-issues#127]
### Version

v2.4.30

### Description

Refund in configuration is empty.

### Expected behaviour

.

### Reproduction steps

```bash
.
```

### Screenshots

![Capture](https://github.com/KB-RolePlay/tools-issues/assets/21173205/a63ec9b3-12ce-47b1-95fb-514c9b7899d8)

**Comment by hugoheml** [comment]
We will rewrite the configuration module.

**Comment by hugoheml** [comment]
New configuration module added.
Issue closed.
