### ISSUE TITLE
problem with permission

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/tools-issues#20]
### Version

v1.2.10

### Description

Not the permissions for the manager of police chef to override police sanctions, when he clicks on the trash his doing nothing

### Expected behaviour

its should remove the sanctions

### Reproduction steps

```bash
1. try to remove sanctions
```

**Comment by talarmin29** [comment]
Issue closed

**Comment by talarmin29** [comment]
Issue closed
