### ISSUE TITLE
not responsive

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/tools-issues#21]
### Version

v1.2.10

### Description

see image is not responsive

### Reproduction steps

```bash
1. 
2. 
3. 
4.
```

### Screenshots

![image](https://user-images.githubusercontent.com/72035382/231241250-72b36bf5-fb86-4cb7-95ca-76ac8cf202d8.png)

**Comment by talarmin29** [comment]
Issue fixed
