### ISSUE TITLE
double logs 

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/tools-issues#23]
### Version

v1.2.10

### Description

double logs for blacklist, see image

### Reproduction steps

```bash
1. 
2. 
3. 
4.
```

### Screenshots

![image](https://user-images.githubusercontent.com/72035382/231241882-a59d52e7-66fc-416c-ba9d-f66d15a4edec.png)

**Comment by talarmin29** [comment]
Issue closed
