### ISSUE TITLE
Config problem

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/tools-issues#25]
### Version

v1.2.10

### Description

see image

### Reproduction steps

```bash
1. 
2. 
3. 
4.
```

### Screenshots

![image](https://user-images.githubusercontent.com/72035382/231242451-580382f4-095e-4292-b615-df15eaf13cba.png)

**Comment by talarmin29** [comment]
Not fixed

![Capture](https://github.com/KB-RolePlay/tools-issues/assets/21173205/a4dc45ec-9f3c-4745-ad43-1ee857b475eb)
