### ISSUE TITLE
Oral Recruitment system

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/tools-issues#27]
### Description

- Configurable Q&A system

- recovery of the single refusal and automatic refusal if the threshold is not met

- in the complete section, see the scale and questions. as well as a location to complete in relation to the question. Make a check box option for a response choice.

- Automatically correct certain answers such as the boxes to be filled in

- Make a correction system by defining additional points and comments. As well as being able to see what is normally required (configurable in the config)

- Make a accept/decline button in the correction moment

- Make a first party information in the form that fills the basic information of the player: rp name, steamid, discord name, maintenance number

- If the person is accepted show a message to add the maintainer as steam friend and then redirect to the staff rules then put all perm

**Comment by hugoheml** [comment]
Application system will be reworked, I close your issue.
