### ISSUE TITLE
False informations

### ISSUE THREAD

**Issue by Bugi-dev** [KB-RolePlay/tools-issues#40]
### Version

v1.2.10

### Description

Bans are added while the person is not ban and by a staff that is not staff

### Expected behaviour

It is false information

### Reproduction steps

```bash
1. check information
```

### Screenshots

![image](https://user-images.githubusercontent.com/72035382/231571460-cdeda4d3-3e6e-4d6e-bbc8-76cf5768d1dd.png)

**Comment by hugoheml** [comment]
Resolved in v2.0.0.
