### ISSUE TITLE
Discord, access to the ticket for the staff. 

### ISSUE THREAD

**Issue by ManonOnAir** [KB-RolePlay/tools-issues#54]
### Version

Discord 

### Description

When a staff member picks up a ticket, he or she does not have permission to see the channel, but the ticket pickup message is sent to the ticket.

### Reproduction steps

```bash
1. Open a ticket
2. Take the ticket (by a person who does not have access to all channels).
```

**Comment by hugoheml** [comment]
Fixed in release `v2.0.5`, thanks for your report!
