### ISSUE TITLE
Game time dashboard

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/tools-issues#59]
### Version

v2.1.6

### Description

Play times not correctly calculated.

### Expected behaviour

Correctly calculated time.

### Reproduction steps

```bash
1. Open dashboard
```

### Screenshots

![image-1685459430806](https://github.com/KB-RolePlay/tools-issues/assets/21173205/f8e55287-fdc8-4819-bebe-c965ae55d13d)

**Comment by hugoheml** [comment]
This comes from old `kbrp-statistics` addon. 
Solved by the new addon that replace them: `kbrp-dashboard`.
I can't do anything about the time > 24h.
