### ISSUE TITLE
Promotion to fire chief

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/tools-issues#61]
### Version

v2.1.6

### Description

When a player is promoted to fire chief, he does not receive permission on discord and IG, he receives a message that he is whitelist mayor.

### Expected behaviour

Permissions given on discord and IG.

### Reproduction steps

```bash
1. Open a player's profile on the dashboard
2. Promote fire chief
```

**Comment by hugoheml** [comment]
Fixed in the Dashboard permissiosn configuration.
