### ISSUE TITLE
Bots KB Support | Claim ticket issue 

### ISSUE THREAD

**Issue by goldendu54** [KB-RolePlay/tools-issues#64]
### Version

Kobralost Support Bot

### Description

the name of the person who took charge of the ticket does not appear correctly

Channel affected for the moment :

[1115072104803610735] / [1114163605554872473] 

### Expected behaviour

the name is displayed normally

### Reproduction steps

```bash
1. Take over the ticket in claim-tickets [1108788619193352326]
2. check in the ticket channel
```

### Screenshots

https://i.imgur.com/xwSyjO8.png

**Comment by hugoheml** [comment]
Comes from translation file, solved in `v2.0.8`, thanks for your report!
