### ISSUE TITLE
Bad text when add a comment while in staff on dashboard

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/tools-issues#73]
### Description

The text isnt translated i guess

### Reproduction steps

```bash
1. Go on the profil of someone (76561199073084071 as example)
2. Add a comment
```

### Screenshots

![image](https://github.com/KB-RolePlay/tools-issues/assets/46120142/c172b03d-74b9-4f98-a16b-9282b785f0de)

**Comment by hugoheml** [comment]
Resolved on release `v2.1.34`.
