### ISSUE TITLE
Complaints transfer

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/tools-issues#74]
### Version

v2.1.7

### Description

Complaints are not forwarded to all moderation members, only to admins.

### Expected behaviour

Available to all moderation members.

### Reproduction steps

```bash
.
```

**Comment by hugoheml** [comment]
Issue comes when the ticket is redirected to moderators.

**Comment by hugoheml** [comment]
Normaly solved on release `v2.1.10`, need to check before close the issue after deployment.

**Comment by hugoheml** [comment]
Problem solved on issue `v2.1.19`. Issue closed.
