### ISSUE TITLE
Dashboard buttons issues

### ISSUE THREAD

**Issue by luzzardik** [KB-RolePlay/tools-issues#76]
### Description

Clicking on the following links will fake signout the user, forcing it to relog through Steam:

- KB dashboard (header icon)
- Get back to home on 403, related to next issue

Clicking on the following links will send to 403 page by default
- User dropdown > Myself

### Reproduction steps

```bash
1. Click on any link said in description
```

**Comment by hugoheml** [comment]
Hey,
I can't reproduce your bugs on version `v2.1.33`, could you please test and keep my informed?

**Comment by luzzardik** [comment]
Can't reproduce either.

**Comment by Kobralost** [comment]
Thanks I close the issue!

**Comment by luzzardik** [comment]
Nevermind, still happening, but not with the "brand" button, only through Avatar dropdown > myself

**Comment by luzzardik** [comment]
This is most likely caused by the target link being `https://dashboard.kobralost-rp.com/admin/2/players/:playerId` and back to home being `https://dashboard.kobralost-rp.com`, which I guess would be a redirection to Steam and doesn't check for currently logged in user.
