### ISSUE TITLE
Staff sanctions (OBS)

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/tools-issues#78]
### Version

v2.1.7

### Description

The moderator doesn't see the severity of his sanction.

### Expected behaviour

The level of severity is seen.

### Reproduction steps

```bash
.
```

### Screenshots

![image](https://github.com/KB-RolePlay/tools-issues/assets/21173205/42412ece-c8cd-4673-91ca-f2784571c2f9)

**Comment by hugoheml** [comment]
Fixed in release `v2.1.10`
