### ISSUE TITLE
Questions demands label is invisible

### ISSUE THREAD

**Issue by luzzardik** [KB-RolePlay/tools-issues#84]
### Description

The "Question" label on demands is invisible being white text and white background

### Reproduction steps

```bash
1. Create an "Other" (Autre) / "Ask" (Question) demand
```

**Comment by hugoheml** [comment]
Thanks for your report, could you please add a screenshot of the problem?

**Comment by luzzardik** [comment]
![image](https://github.com/KB-RolePlay/tools-issues/assets/70561001/dd202030-92ed-4e6e-88ae-0e85aac03835)

**Comment by hugoheml** [comment]
Normaly resolved, could you please check?

**Comment by luzzardik** [comment]
✅ Resolved; 24/06/2023 13:25:17 (TZ Europe/Paris).
