### ISSUE TITLE
"Marquer tout comme lu>"

### ISSUE THREAD

**Issue by luzzardik** [KB-RolePlay/tools-issues#85]
### Description

Text should be "Marquer tout comme lu", the ">" removed.

### Reproduction steps

```bash
1. Click on notifications
```

### Screenshots

![image](https://github.com/KB-RolePlay/tools-issues/assets/70561001/66a9eba0-75be-4166-9ff9-190a8a62a7e6)

**Comment by hugoheml** [comment]
Issue resolved in version `v2.1.34`.
Thanks for your report!
