### ISSUE TITLE
make inactive warn bug 

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/tools-issues#87]
### Version

v2.1.30

### Description

When you correct a warn as "inactive" (by unchecking the box) it just load infinitely and log out an error saying "Une erreur est survenue lors de la récupération des données". If you refresh the page, the warn is unactive.

### Expected behaviour

You shouldn't have an error and an infinite loading. 

### Reproduction steps

```bash
1. Go the "casier" of someone
2. Try to make a warn inactive
```

### Screenshots

![image](https://github.com/KB-RolePlay/tools-issues/assets/46120142/24e8e199-42ba-479d-b73c-3371173a0d7a)

**Comment by hugoheml** [comment]
I can't reproduce the problem, please go the `Network` tab on the `Developer Tools` and do a screenshot of the `Preview` and `Headers` tabs.

**Comment by Pikabois** [comment]
The only thing i get back is this, so i guess it wont help you sorry xD
![image](https://github.com/KB-RolePlay/tools-issues/assets/46120142/349683d7-d0e5-40f5-9097-a7f2a077b087)
![image](https://github.com/KB-RolePlay/tools-issues/assets/46120142/2eb9ea70-2a15-4ff2-8c23-6fdf0871c174)
![image](https://github.com/KB-RolePlay/tools-issues/assets/46120142/d9bc5e5d-8467-44bc-bf08-2e228a339796)

**Comment by Pikabois** [comment]
Hey @hugoheml, i have a video if you want to see what happen exactly

**Comment by talarmin29** [comment]
Issue fixed
